from selenium.webdriver.common.by import By

class BurgerLocators():
    personal_account = By.LINK_TEXT, "Личный Кабинет"
    registration_button = By.XPATH, ".//a[@href='/register']"
    registration_name = By.XPATH, ".//label[text()='Имя']/following-sibling::input"
    registration_email = By.XPATH, ".//label[text()='Email']/following-sibling::input"
    registration_password = By.XPATH, ".//fieldset/div/div/input[@name='Пароль']"
    registration_text_btn = By.XPATH, ".//button[text()='Зарегистрироваться']"
    login_email = By.XPATH, ".//input[@name='name']"
    login_password = By.XPATH, ".//input[@name='Пароль']"
    login_button = By.XPATH, ".//button[text()='Войти']"
    constructor = By.LINK_TEXT, "Конструктор"
    wrong_password = By.XPATH, ".//p[text()='Некорректный пароль']"
    exit_button = By.XPATH, ".//button[text()='Выход']"
    order_button = By.XPATH, ".//button[text()='Оформить заказ']"
    recovery_password = By.LINK_TEXT, "Восстановить пароль"
    login_button_entrance = By.LINK_TEXT, "Войти"
    enter_account = By.XPATH, ".//button[text()='Войти в аккаунт']"
    sauces = By.XPATH, ".//span[text()='Соусы']"
    name_sauces = By.XPATH, "//p[text()='Соус традиционный галактический']"
    rolls = By.XPATH, ".//span[text()='Булки']"
    name_rolls = By.XPATH, ".//p[text()='Флюоресцентная булка R2-D3']"
    fillings = By.XPATH, ".//span[text()='Начинки']"
    name_fillings = By.XPATH, ".//p[text()='Мини-салат Экзо-Плантаго']"
    logo = By.CLASS_NAME, "AppHeader_header__logo__2D0X2"
